# Generated by Django 5.1.6 on 2025-02-24 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dates_info',
            name='selected_date',
        ),
        migrations.AlterField(
            model_name='dates_info',
            name='available_dates',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='dates_info',
            name='unavailable_dates',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Selected_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_dates', models.CharField(max_length=50, verbose_name='선택한 날짜')),
                ('calendar_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appoint.appointment', verbose_name='달력 코드')),
            ],
        ),
    ]
