# Generated by Django 5.1.6 on 2025-02-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0002_remove_dates_info_selected_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates_info',
            name='user',
            field=models.CharField(default=1, max_length=50, verbose_name='사용자'),
            preserve_default=False,
        ),
    ]
