# Generated by Django 5.1.6 on 2025-03-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0003_dates_info_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='피드백 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
